### ISSUE TITLE
Broken pipe error when piping the output to `head`

### ISSUE THREAD

**Issue by miikka** [jarcane/wf#2]
Hey, I just used wf for some data exploration and it was pretty useful! I tried to look up the most frequent word in a text and piped wf's output to head. I got the following error message. The error probably happens because head exits after it has printed the requested number of lines. I would expect a command-line tool like wf to handle piping to head gracefully.

```
% wf -f < text.txt | head -1
the 2228
thread 'main' panicked at 'failed printing to stdout: Broken pipe (os error 32)', libstd/io/stdio.rs:692:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

I'm using wf 0.2.0 on macOS.

**Comment by jarcane** [comment]
Hmm. That is odd. I don't have a Mac anymore to try this, but I can mess about on WSL. 

Out of curiosity, what do you get if instead you do `cat text.txt | wf -f | head -1`?

**Comment by miikka** [comment]
It gives me the same error. I googled a bit and turns out other people are having the same problem: https://github.com/rust-lang/rust/issues/46016

**Comment by jarcane** [comment]
OK, thanks. I'll try and have a look at that tonight. Looks like there might be a work around using `write!` instead of `println!`.

**Comment by jarcane** [comment]
I've pushed a new version 0.2.1 that fixes the bug by adding the necessary error checking and early exit behavior with `writeln!`. 

You can run `cargo install wf --force` to update.

**Comment by miikka** [comment]
Thanks! It works now.
